version: "3.7"

services:

  db:
    image: postgres:14.1-alpine
    container_name: postgreSQL
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: cloud
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - /opt/psql/dada:/var/lib/postgresql/data

  redis:
    image: redis:6.0.20-alpine3.18
    container_name: redisServer
    restart: always
    ports:
      - "6379:6379"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./storage/redis/data:/data

  app:
    build: ./
    image: cloud:latest
#      context: .
#      dockerfile: Dockerfile
    container_name: cloudService
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cloud?currentSchema=cloud
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345678
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_LIQUIBASE_URL: jdbc:postgresql://db:5432/cloud
      SPRING_LIQUIBASE_USER: postgres
      SPRING_LIQUIBASE_PASSWORD: 12345678
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    volumes:
      - /app/logs:/app/logs
    depends_on:
      - db
      - redis